Add code from tutorial
wolox-training/gs-vue pull request #12
Opened 2018-08-15 13:15 UTC by GiulianoScaglioni

# Summary
- App is created with CRA (`create-react-app --scripts-version wolox-react-scripts`)
- Add code from tutorial ([Tutorial: Intro to React](https://reactjs.org/tutorial/tutorial.html))
- Code is splitted into components
- Code follows training guidelines
- Tests run ok
- Div grouping multiple tags was replaced with Fragment

# Trello Card
- [ENV I - create-react-app](https://trello.com/c/jTGikxkx)
- [Estructura de carpetas](https://trello.com/c/vHCqeTOM)
- [React App - Tic Tac Toe](https://trello.com/c/cMbwR8Da)

# Screenshot
![screenshot from 2018-08-15 10-11-03](https://user-images.githubusercontent.com/41913560/44149795-b1151260-a073-11e8-9a76-9c5ae356d208.png)

2018-08-15 14:10 UTC, damfinkel requested changes

2018-08-15 14:10 UTC, damfinkel commented on training-react/src/app/components/App/index.js
> +class App extends Component {
we are not using this file, remove it

2018-08-15 14:10 UTC, damfinkel commented on training-react/src/app/components/Board/index.js
> +  // eslint-disable-next-line
- Why does this need to be in a separate function? We might as well have it inside the render method directly:
```
...
<div className={style.boardRow}>
  <Square />
</div>
...
```
- renderSquare receives a parametr it's not using
- I think we can remove the linter comment

2018-08-15 14:10 UTC, damfinkel commented on training-react/src/app/components/Board/index.js
> +    const status = 'Next player: X';
- If you need a constant, you can declare it as such outside the component.
- Next player might be O, we need to change depending on which player's turn is

2018-08-15 14:10 UTC, damfinkel commented on training-react/src/app/components/Board/index.js
> +          {this.renderSquare(0)}
the parameter isn't being used, and as I commented above, I'd call <Square /> directly here

2018-08-15 14:10 UTC, damfinkel commented on training-react/src/app/components/Board/styles.scss
> +  display: table;
Why display table? We usually try to use flexbox when possible

2018-08-15 14:10 UTC, damfinkel commented on training-react/src/app/components/Game/index.js
> +        <div>
I don't think this div is necessary. We can avoid it and render the Board component directly

2018-08-15 14:10 UTC, damfinkel commented on training-react/src/app/components/Square/styles.scss
> +  margin-right: -1px;
Why this negative margins? If it's because of the border, border isn't part of the inner content size of the component (so, if the element has defined for instance 100px by 100px and 10px of border, it has 100x100 of content AND 10px of border).

2018-08-15 14:10 UTC, damfinkel commented on training-react/src/index.js
> +import Game from '~components/Game'; // eslint-disable-line import/first
instead of disabling the linter, move this line above the index.scss file as the linter asks

2018-08-16 19:37 UTC, damfinkel requested changes

2018-08-16 19:37 UTC, damfinkel commented on training-react/src/app/components/Square/styles.scss
> +  margin-top: -1px;
Why this negative margins? If it's because of the border, border isn't part of the inner content size of the component (so, if the element has defined for instance 100px by 100px and 10px of border, it has 100x100 of content AND 10px of border).

2018-08-16 19:37 UTC, damfinkel commented on training-react/src/app/components/Board/index.js
> +    const cells = Array(9);
Little nicer and more "functional":

```
render() {
  return (
    <div className={style.board}>
      {this.props.squares.map(squareId => <Square key={squareId} pos={squareId} ... />)} // Change the squares so the array has as element the squareId
    </div>
  )
}
```

2018-08-16 19:37 UTC, damfinkel commented on training-react/src/app/components/Game/index.js
> +    history: [{ squares: Array(9).fill(null) }],
here you can change this for `Array.from(Array(10)).map((element, index) => `square${index}` )` so you simulate an "id"

2018-08-16 19:37 UTC, damfinkel commented on training-react/src/app/components/Game/utils.js
> +  for (let i = 0; i < lines.length; i += 1) {
```
const winner = lines.filter(line => {
  const [a, b, c] = lines[i];
  return squares[a] && squared[b] && squares[c] && squares[a] === squares[b] && squares[a] === squares[c]
})

if (winner) {
  return winner;
}

return squares.every(square => square) ? 'Tie!' : null;
```

2018-08-16 19:37 UTC, damfinkel commented on training-react/src/app/components/Game/index.js
> +  handleClick(i) {
prefer arrow functions for instance methods (only lifecycle methods should be normal functions):

`handleClick = (i) => {...}`

Apply this to the rest of the components

2018-08-16 19:37 UTC, damfinkel commented on training-react/src/app/components/Game/index.js
> +    const winner = calculateWinner(current.squares);
if there's a winner or not should be saved in the state, to avoid calculating it each time render() is called. In handleClick, you could set also a `winner` state and just get it from there instead of recalculating it.

2018-08-16 19:37 UTC, damfinkel commented on training-react/src/app/components/Game/index.js
> +        <li className={style.stepItem} key={move}>
index as key is discouraged, as it could lead to bugs: https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318

Use step to identify the steps, if you can't with this current implementation, you may have to change the `step`

2018-08-16 19:37 UTC, damfinkel commented on training-react/src/app/components/Game/index.js
> +    let status;
Avoid logic when possible in the render() method. Try to limit everything to JSX or simple constant asignment. If you need more logic, you can have helper methods to easily fetch the final stuff you are going to render.
Also, try to leave the JSX with the same order it'll be rendered. It's easier to understand if you move the `moves` part inside the div it'll be rendered in instead of assigning it to a variable first and then use that variable:

```
render() {
  return (
    <div className={style.game}>
      <Board squares={current.squares} onClick={i => this.handleClick(i)} />
      <div className={style.gameInfo}>
        <div className={style.gameStatus}>
          {getTitleText(this.state.winner, this.state.xIsNext)}
        </div>
        <ul className={style.stepList}>
          {history.map((step, move) => { ... })}
        </ul>
  )
}
```

2018-08-16 19:37 UTC, damfinkel commented on training-react/src/app/components/Game/styles.scss
> +    composes: stepButton;
we are using sass modules (`composes` is from css modules), there's a nicer way to do this:

`@extend stepButton`

2018-08-16 19:37 UTC, damfinkel commented on training-react/src/app/components/Game/styles.scss
> +    &:hover {
enter between selectors and previous line

2018-08-16 19:37 UTC, damfinkel commented on training-react/src/app/components/Game/styles.scss
> +    background-color: rgba(255, 255, 255, 0.1);
indentation is not consistant. Use always 2 spaces

2018-08-16 19:37 UTC, damfinkel commented on training-react/src/app/components/Square/styles.scss
> +    composes: common;
same, use @extend

2018-08-16 19:37 UTC, damfinkel commented on training-react/src/scss/variables/colors.scss
> +$white: #FFF;
There are some colors (rgba colors) that you could define here:

`$white-alpha: rgba($white, 0.3);` 

Define those here and use that variables

2018-08-22 19:13 UTC, damfinkel commented on training-react/src/app/components/Board/index.js
> +            onClick={() => this.props.onClick(square.id)}
we try to avoid inline functions in props, as each time the render is called, the function is created again. Instead, you can fix the reference:
```
handleClick = () => this.props.onClick(square.id)

render() {
  return (
    ...
    onClick={this.handleClick()}
  )
}
```

2018-08-22 19:13 UTC, damfinkel commented on training-react/src/app/components/Board/index.js
> +  squares: PropTypes.arrayOf(Object),
you should specify with `shape` how the squares are formed:

```
squares: PropTypes.arrayOf(PropTypes.shape({ id: PropTypes.number, value: PropTypes.string })).isRequired //something like this
```

2018-08-22 19:13 UTC, damfinkel commented on training-react/src/app/components/Board/index.js
> +  onClick: PropTypes.func
.isRequired

2018-08-22 19:13 UTC, damfinkel commented on training-react/src/app/components/Game/index.js
> +      return status === 'T' ? 'Tie!' : `Winner: ${status}`;
extract 'T' to a constant:

export const TIE = 'T'

2018-08-22 19:13 UTC, damfinkel commented on training-react/src/app/components/Game/index.js
> +        <Board squares={current.squares} onClick={i => this.handleClick(i)} />
this should be passed differently to avoid inline functions:

`onClick={this.handleClick} // passing the reference of the function``

Then, in the board component:
```
handleClick = (id) => this.props.onClick(id);
render() {
  return (
    <Square ... onClick={this.handleClick}>
  )
}
```

In Square:

```
handleClick = () => this.props.onClick(this.props.pos);
onClick={this.handleClick}
```

Note that each handle click does something different. The first one calculates the winner (might as well be named `updateGame` or sth. The second one receives an index and calls the first one with tht index. The last one is the real click handler, which has the square id as index and passes that to the second handler, so it can pass it to the one that updates the game

2018-08-22 19:13 UTC, damfinkel commented on training-react/src/app/components/Game/utils.js
> +  return squares.every(square => square.value) ? 'T' : null;
use the constant I named before, to avoid possible errors by having the same constant hardcoded in more than one place

2018-08-22 19:13 UTC, damfinkel commented on training-react/src/app/components/Game/index.js
> +    const squares = current.squares.map(elem => ({ ...elem }));
why are you making a copy here?

2018-08-27 04:41 UTC, damfinkel approved these changes

2018-08-27 04:41 UTC, damfinkel commented on training-react/src/app/components/Board/index.js
> +  handleClick = this.props.onClick;
unnecessary, given that you could just ` <Square .. onClick={this.props.onClick} />`

2018-08-27 04:41 UTC, damfinkel commented on training-react/src/app/components/Game/index.js
> +    const squares = [...current.squares];
I don't get why you just don't assign current.squares

`const squares = current.squares`

2018-08-27 12:11 UTC, GiulianoScaglioni commented on training-react/src/app/components/Game/index.js
> +    const squares = [...current.squares];
That array is then stored in history. If I keep the same one, then when I make changes to it, I'll be changing past states. That's why I also need to copy the square I'm modifying:
```
squares[i] = { ...squares[i], value: this.state.xIsNext ? 'X' : 'O' };
```

2018-08-27 12:17 UTC, merged