Redux
wolox-training/gs-vue pull request #13
Opened 2018-08-22 18:25 UTC by GiulianoScaglioni

# Summary
- State is stored by Redux
- Reducers implemented
- Game gets state connecting to Redux and passes it to childs via props (as was already done). Connecting each component might be better but the point was to reduce the written code.

# Trello Card
[Redux I - Actions, Reducers, Store [TODO: Finger]](https://trello.com/c/o4fukriF)

# Screenshot
As seen below, state is changed via actions (MOVE_DONE & TIME_TRAVEL).

![redux](https://user-images.githubusercontent.com/41913560/44482461-bfafcf80-a61e-11e8-9a13-98ab19db7278.png)

2018-08-27 05:10 UTC, damfinkel requested changes

2018-08-27 05:10 UTC, damfinkel commented on training-react/src/app/components/Game/index.js
> +import { actionCreators } from '../../../redux/game/actions';
with actionCreators, we like to change the name of the imported variable like this:

`import { actionCreators as gameActions }`

2018-08-27 05:10 UTC, damfinkel commented on training-react/src/app/components/Game/index.js
> +    this.props.dispatch(actionCreators.moveDone(i));
I personally prefer using mapDispatchToProps rather than the dispatch prop directly, because doing this encourages to dispatch all over the component's code as your code gets bigger. This would be fine for this example, but for the sake of practising let's just make the change:

```
handleClick = i => this.props.performMove(i);

// This goes after mapStateToProps
const mapDispatchToProps = dispatch => ({
  performMove: i => dispatch(gameActions.moveDone(i))
})
;

export default connect(mapStateToProps, mapDispatchToProps)(Game);
```

2018-08-27 05:10 UTC, damfinkel commented on training-react/src/app/components/Game/index.js
> +    this.props.dispatch(actionCreators.timeTravel(step));
same here, move to mapDispatch

2018-08-27 05:10 UTC, damfinkel commented on training-react/src/app/components/Game/index.js
> +  history: Array,
you are not using proptypes here, you're using javascript classes, and I think this would throw some warnings in the console. PropTypes are imported from the `prop-types` library:
```
import PropTypes from 'prop-types';

Game.propTypes = {
  history: PropTypes.array,

  xIsNext: PropTypes.bool,
  ...
}
```

Prop types are useful for documentation and to check in runtime if some prop is being mishandled by passing something that's not expected. Docs on PropTypes: https://reactjs.org/docs/typechecking-with-proptypes.html

2018-08-27 05:10 UTC, damfinkel commented on training-react/src/redux/board/reducer.js
> +import squareReducer from '../square/reducer';
Just because a convention of ours, we capitalize all folder names, so this file's parent folder should be called `Board`. Same goes for other folders.

2018-08-27 05:10 UTC, damfinkel commented on training-react/src/redux/game/actions.js
> +  MOVE_DONE: '@@game/MOVE_DONE',
namespace should be uppercase too

2018-08-27 05:10 UTC, damfinkel commented on training-react/src/redux/game/actions.js
> +      squareId
by convention, we always send this data in a `payload` key:
`return { type: actions.MOVE_DONE, payload: squareId }`

And then use `action.type` and `action.payload`

2018-08-27 05:10 UTC, damfinkel commented on training-react/src/redux/game/actions.js
> +      stepId
same here

2018-08-27 05:10 UTC, damfinkel commented on training-react/src/redux/game/reducer.js
> +import calculateWinner from '../../app/components/Game/utils';
I think you only use this file here, so I'd move it to this folder instead of keeping it there

2018-08-27 05:10 UTC, damfinkel commented on training-react/src/redux/board/reducer.js
> +        squares: state.squares.map(elem => squareReducer(elem, action, xIsNext))
reducers shouldn't be coupled this way. Each reducer should be independent on the others. How you should model this, is that each "model" has it's own reducer. So I would model this the following way:
- A Square reducer, that has the squares
- A Game reducer that has the general game state (like winner, who's next and currentStep)

The game reducer doesn't know nor affects the Square's state. If you need to affect both slices of the store, you can call a Game action and a Square action:

```
// Obviuosly this doesn't work but it's an example of how you can use more than one actionCreator
import { actionCreators as squareActions } from '~redux/Square/actions';
import { actionCreators as gameActions } from '~redux/Game/actions';
handleClick = (i) => {
  this.props.dispatch(squareActions.setSquare(i, 'X'));
  this.props.dispatch(gameActions.performMove());
}
```

Finally, you can merge reducers by using the combineReducers method. This will change you mapStateToProps:
```
const rootReducer = combineReducers([squareReducer, gameReducer]);

const store = createStore(
  rootReducer,
  // eslint-disable-next-line
  window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()
);

// Now, for example to get the squares and current step:
const mapStateToProps  = state => ({
  squares: state.square.squares
  currentStep: state.game.currentStep
})
```

On Monday we can discuss this further, it can be difficult to understand by only reading it.

2018-08-28 17:36 UTC, GiulianoScaglioni commented
**History** is now handled in a different way. Each square contains the step in which it was marked. To "time travel", only the `currentStep` is changed (squares with a mark order higher than the current step can be marked)

2018-08-29 17:33 UTC, damfinkel approved these changes

2018-08-29 18:20 UTC, merged