Session management
wolox-training/gs-vue pull request #22
Opened 2019-01-11 18:48 UTC by GiulianoScaglioni

## Summary
- Style changes to add auth layout
- Added auth view
- Added localstorage service
- Save token in localstorage after successful login
- Remove token from localstorage when logout

## Screenshot
![test-login-logout](https://user-images.githubusercontent.com/41913560/51053345-20cd4500-15b8-11e9-80c0-5dfda9c29041.gif)

## Trello card
[https://trello.com/c/SCmibIwj/24-session-management-logout](https://trello.com/c/SCmibIwj/24-session-management-logout)

2019-01-11 19:23 UTC, FrankIglesias requested changes

2019-01-11 19:23 UTC, FrankIglesias commented on training-vue/wolox-books/src/App.vue
> +  margin: 0;
use an equalizer like [this](https://www.npmjs.com/package/wolox-equalizer)

2019-01-11 19:23 UTC, FrankIglesias commented on training-vue/wolox-books/src/components/Dialog.vue
> +#header {
avoid using ids in styles

2019-01-11 19:23 UTC, FrankIglesias commented on training-vue/wolox-books/src/components/Dialog.vue
> +  #title {
add empty line after curly brace

2019-01-11 19:23 UTC, FrankIglesias commented on training-vue/wolox-books/src/components/Dialog.vue
> +    width: 80%;
why this 80%?

2019-01-11 19:23 UTC, FrankIglesias commented on training-vue/wolox-books/src/components/Header.vue
> +.logo {
add empty line

2019-01-11 19:23 UTC, FrankIglesias commented on training-vue/wolox-books/src/components/Header.vue
> +.title {
same

2019-01-11 19:23 UTC, FrankIglesias commented on training-vue/wolox-books/src/components/Header.vue
> +.header {
same

2019-01-11 19:23 UTC, FrankIglesias commented on training-vue/wolox-books/src/components/Header.vue
> +  letter-spacing: 2px;
why this letter spacing?

2019-01-11 19:23 UTC, FrankIglesias commented on training-vue/wolox-books/src/scss/commons/button.scss
> +  text-decoration: none;
remove this and use the equalizer

2019-01-11 19:23 UTC, FrankIglesias commented on training-vue/wolox-books/src/views/Register.vue
> +.container {
add empty line before this

2019-01-11 19:23 UTC, FrankIglesias commented on training-vue/wolox-books/src/views/Register.vue
> +    Dialog
lower case in components

2019-01-11 19:23 UTC, FrankIglesias commented on training-vue/wolox-books/src/views/Auth.vue
> +    Header
lower case in components

2019-01-11 20:13 UTC, mcallegari10 requested changes

2019-01-11 20:13 UTC, mcallegari10 commented on training-vue/wolox-books/src/components/Dialog.vue
> +#header {
Style using only classes, don't use ids for that

2019-01-11 20:13 UTC, mcallegari10 commented on training-vue/wolox-books/src/components/Dialog.vue
> +  #logo {
Same here

2019-01-11 20:13 UTC, mcallegari10 commented on training-vue/wolox-books/src/components/Dialog.vue
> +  #title {
And here

2019-01-11 20:13 UTC, mcallegari10 commented on training-vue/wolox-books/src/components/Dialog.vue
> +      span#title BOOKS
Use pipe notation for the plain text. Should be like:

```pug
span
  | BOOKS
```

2019-01-11 20:13 UTC, mcallegari10 commented on training-vue/wolox-books/src/components/Dialog.vue
> +  justify-self: center;
`justify-self` is not needed

2019-01-11 20:13 UTC, mcallegari10 commented on training-vue/wolox-books/src/components/Header.vue
> +        span.title BOOKS
Use pipe notation here

2019-01-11 20:13 UTC, mcallegari10 commented on training-vue/wolox-books/src/components/Header.vue
> +        button.btn-link(@click='logout') Logout
Same here

2019-01-11 20:13 UTC, mcallegari10 commented on training-vue/wolox-books/src/views/Auth.vue
> +  name: 'login',
The name should be the same as the name of the component

2019-01-11 20:13 UTC, mcallegari10 commented on training-vue/wolox-books/src/views/Login.vue
> +        label(:class="['label', { 'text-error': $v.email.$error }]") Email
Pipe notation please

2019-01-11 20:13 UTC, mcallegari10 commented on training-vue/wolox-books/src/views/Login.vue
> +        label(:class="['label', { 'text-error': $v.password.$error }]") Password
Same here

2019-01-11 20:13 UTC, mcallegari10 commented on training-vue/wolox-books/src/views/Login.vue
> +        button.btn-wolox(type='submit') Login
Same here

2019-01-11 20:13 UTC, mcallegari10 commented on training-vue/wolox-books/src/views/Login.vue
> +      router-link.btn-wolox-outline(to='/sign-up') Sign up
Same here

2019-01-11 20:13 UTC, mcallegari10 commented on training-vue/wolox-books/src/components/Dialog.vue
> +  name: 'Dialog'
I think this is not a goo name. Try `Navbar`. Also, it's more like an stateless component so there's no actual need for this `script` section

2019-01-11 20:13 UTC, mcallegari10 commented on training-vue/wolox-books/src/views/Register.vue
> +  flex-direction: row;
No need for this

2019-01-11 20:13 UTC, mcallegari10 commented on training-vue/wolox-books/src/views/Register.vue
>  }
Remember to leave a space between classes

2019-01-11 20:13 UTC, mcallegari10 commented on training-vue/wolox-books/src/views/Register.vue
> +    Dialog
I think this should be indented at the same level as the form

2019-01-11 20:13 UTC, mcallegari10 commented on training-vue/wolox-books/src/views/Login.vue
> +  flex-direction: row;
No need for this

2019-01-11 20:13 UTC, mcallegari10 commented on training-vue/wolox-books/src/views/Register.vue
> +.container {
I'm seeing this repeated, I think you should abstract it to a `commons` or a SCSS component

2019-01-14 15:55 UTC, FrankIglesias requested changes

2019-01-14 15:55 UTC, FrankIglesias commented on training-vue/wolox-books/src/App.vue
> +.app {
are you assigning this class to any component?

2019-01-14 15:55 UTC, FrankIglesias commented on training-vue/wolox-books/src/components/WoloxDialog.vue
> +      span.title BOOKS
span.title
  | BOOKS

2019-01-14 15:55 UTC, FrankIglesias commented on training-vue/wolox-books/src/components/WoloxDialog.vue
> +<template lang="pug">
why woloxdialog?

2019-01-14 15:55 UTC, FrankIglesias commented on training-vue/wolox-books/src/components/WoloxNavbar.vue
> +        img(src='../assets/wolox_logo.svg')
add an alt here

2019-01-14 15:55 UTC, FrankIglesias commented on training-vue/wolox-books/src/components/WoloxNavbar.vue
> +.header-container {
this should be fixed

2019-01-14 15:55 UTC, FrankIglesias commented on training-vue/wolox-books/src/router.js
> +      component: () => import('./views/Auth.vue')
Rename this component to dashboard

2019-01-14 15:55 UTC, FrankIglesias commented on training-vue/wolox-books/src/router.js
> +      path: '/auth',
`/`

2019-01-14 15:55 UTC, FrankIglesias commented on training-vue/wolox-books/src/scss/commons/layout.scss
> +.container {
maybe this layout is the same as `.app`

2019-01-14 15:55 UTC, FrankIglesias commented on training-vue/wolox-books/src/views/Login.vue
> +              this.$router.push({ name: 'auth' })
'/'

2019-01-14 17:04 UTC, GiulianoScaglioni commented on training-vue/wolox-books/src/components/WoloxDialog.vue
> +<template lang="pug">
It's like a dialog box, maybe `card` its a better name?? and i used wolox because i read it should have more than one word to not conflict with html tags

2019-01-15 18:49 UTC, FrankIglesias requested changes

2019-01-15 18:49 UTC, FrankIglesias commented on training-vue/wolox-books/src/views/Login.vue
> +        button.btn-wolox(type='submit')
this type is the default one

2019-01-15 18:49 UTC, FrankIglesias commented on training-vue/wolox-books/src/views/Register.vue
> +        button.btn-wolox(type='submit')
same

2019-01-15 19:55 UTC, FrankIglesias requested changes

2019-01-15 19:55 UTC, FrankIglesias commented on training-vue/wolox-books/src/components/WoloxDialog.vue
> +<template lang="pug">
Rename this component to dashboard

2019-01-15 20:11 UTC, FrankIglesias approved these changes

2019-01-15 20:56 UTC, merged